export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_PROFILE = 'GET_PROFILE';

export const GET_MESSAGES_LOADING = 'GET_MESSAGES_LOADING';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAIL = 'GET_MESSAGES_FAIL';

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAIL = 'ADD_MESSAGE_FAIL';

export const DELETE_MESSAGE_LOADING = 'DELETE_MESSAGE_LOADING';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

export const EDIT_MESSAGE_LOADING = 'EDIT_MESSAGE_LOADING';
export const EDIT_MESSAGE_SUCCESS = 'EDIT_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_FAIL = 'EDIT_MESSAGE_FAIL';
export const CLEAR_MESSAGE_ERROR = 'CLEAR_MESSAGE_ERROR';

export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const RESEED_DATABASE_LOADING = 'RESEED_DATABASE_LOADING';
export const RESEED_DATABASE_SUCCESS = 'RESEED_DATABASE_SUCCESS';
export const RESEED_DATABASE_FAIL = 'RESEED_DATABASE_FAIL';

export const GET_PATIENTS_LOADING = 'GET_PATIENTS_LOADING';
export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const ADD_PATIENT_LOADING = 'ADD_PATIENT_LOADING';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAIL = 'ADD_PATIENT_FAIL';

export const DELETE_PATIENT_LOADING = 'DELETE_PATIENT_LOADING';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAIL = 'DELETE_PATIENT_FAIL';

export const EDIT_PATIENT_LOADING = 'EDIT_PATIENT_LOADING';
export const EDIT_PATIENT_SUCCESS = 'EDIT_PATIENT_SUCCESS';
export const EDIT_PATIENT_FAIL = 'EDIT_PATIENT_FAIL';

export const GET_SPECS_LOADING = 'GET_SPECS_LOADING';
export const GET_SPECS_SUCCESS = 'GET_SPECS_SUCCESS';
export const GET_SPECS_FAIL = 'GET_SPECS_FAIL';

export const ADD_SPEC_LOADING = 'ADD_SPEC_LOADING';
export const ADD_SPEC_SUCCESS = 'ADD_SPEC_SUCCESS';
export const ADD_SPEC_FAIL = 'ADD_SPEC_FAIL';

export const DELETE_SPEC_LOADING = 'DELETE_SPEC_LOADING';
export const DELETE_SPEC_SUCCESS = 'DELETE_SPEC_SUCCESS';
export const DELETE_SPEC_FAIL = 'DELETE_SPEC_FAIL';

export const EDIT_SPEC_LOADING = 'EDIT_SPEC_LOADING';
export const EDIT_SPEC_SUCCESS = 'EDIT_SPEC_SUCCESS';
export const EDIT_SPEC_FAIL = 'EDIT_SPEC_FAIL';

export const GET_DOCTORS_LOADING = 'GET_DOCTORS_LOADING';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_FAIL = 'GET_DOCTORS_FAIL';

export const ADD_DOCTOR_LOADING = 'ADD_DOCTOR_LOADING';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS';
export const ADD_DOCTOR_FAIL = 'ADD_DOCTOR_FAIL';

export const DELETE_DOCTOR_LOADING = 'DELETE_DOCTOR_LOADING';
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS';
export const DELETE_DOCTOR_FAIL = 'DELETE_DOCTOR_FAIL';

export const EDIT_DOCTOR_LOADING = 'EDIT_DOCTOR_LOADING';
export const EDIT_DOCTOR_SUCCESS = 'EDIT_DOCTOR_SUCCESS';
export const EDIT_DOCTOR_FAIL = 'EDIT_DOCTOR_FAIL';

export const GET_SERVICES_LOADING = 'GET_SERVICES_LOADING';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAIL = 'GET_SERVICES_FAIL';

export const ADD_SERVICE_LOADING = 'ADD_SERVICE_LOADING';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL';

export const DELETE_SERVICE_LOADING = 'DELETE_SERVICE_LOADING';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE_FAIL';

export const EDIT_SERVICE_LOADING = 'EDIT_SERVICE_LOADING';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAIL = 'EDIT_SERVICE_FAIL';

export const GET_TYPES_LOADING = 'GET_TYPES_LOADING';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';

export const ADD_TYPE_LOADING = 'ADD_TYPE_LOADING';
export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS';
export const ADD_TYPE_FAIL = 'ADD_TYPE_FAIL';

export const DELETE_TYPE_LOADING = 'DELETE_TYPE_LOADING';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';

export const EDIT_TYPE_LOADING = 'EDIT_TYPE_LOADING';
export const EDIT_TYPE_SUCCESS = 'EDIT_TYPE_SUCCESS';
export const EDIT_TYPE_FAIL = 'EDIT_TYPE_FAIL';

export const GET_SERVICE_TYPES_LOADING = 'GET_SERVICE_TYPES_LOADING';
export const GET_SERVICE_TYPES_SUCCESS = 'GET_SERVICE_TYPES_SUCCESS';
export const GET_SERVICE_TYPES_FAIL = 'GET_SERVICE_TYPES_FAIL';

export const ADD_SERVICE_TYPE_LOADING = 'ADD_SERVICE_TYPE_LOADING';
export const ADD_SERVICE_TYPE_SUCCESS = 'ADD_SERVICE_TYPE_SUCCESS';
export const ADD_SERVICE_TYPE_FAIL = 'ADD_SERVICE_TYPE_FAIL';

export const DELETE_SERVICE_TYPE_LOADING = 'DELETE_SERVICE_TYPE_LOADING';
export const DELETE_SERVICE_TYPE_SUCCESS = 'DELETE_SERVICE_TYPE_SUCCESS';
export const DELETE_SERVICE_TYPE_FAIL = 'DELETE_SERVICE_TYPE_FAIL';

export const EDIT_SERVICE_TYPE_LOADING = 'EDIT_SERVICE_TYPE_LOADING';
export const EDIT_SERVICE_TYPE_SUCCESS = 'EDIT_SERVICE_TYPE_SUCCESS';
export const EDIT_SERVICE_TYPE_FAIL = 'EDIT_SERVICE_TYPE_FAIL';

export const GET_LAB_RESULTS_LOADING = 'GET_LAB_RESULTS_LOADING';
export const GET_LAB_RESULTS_SUCCESS = 'GET_LAB_RESULTS_SUCCESS';
export const GET_LAB_RESULTS_FAIL = 'GET_LAB_RESULTS_FAIL';

export const GET_LAB_RESULT_LOADING = 'GET_LAB_RESULT_LOADING';
export const GET_LAB_RESULT_SUCCESS = 'GET_LAB_RESULT_SUCCESS';
export const GET_LAB_RESULT_FAIL = 'GET_LAB_RESULT_FAIL';

export const ADD_LAB_RESULT_LOADING = 'ADD_LAB_RESULT_LOADING';
export const ADD_LAB_RESULT_SUCCESS = 'ADD_LAB_RESULT_SUCCESS';
export const ADD_LAB_RESULT_FAIL = 'ADD_LAB_RESULT_FAIL';

export const DELETE_LAB_RESULT_LOADING = 'DELETE_LAB_RESULT_LOADING';
export const DELETE_LAB_RESULT_SUCCESS = 'DELETE_LAB_RESULT_SUCCESS';
export const DELETE_LAB_RESULT_FAIL = 'DELETE_LAB_RESULT_FAIL';

export const EDIT_LAB_RESULT_LOADING = 'EDIT_LAB_RESULT_LOADING';
export const EDIT_LAB_RESULT_SUCCESS = 'EDIT_LAB_RESULT_SUCCESS';
export const EDIT_LAB_RESULT_FAIL = 'EDIT_LAB_RESULT_FAIL';

export const GET_APPOINTMENT_LOADING = 'GET_APPOINTMENT_LOADING';
export const GET_APPOINTMENT_SUCCESS = 'GET_APPOINTMENT_SUCCESS';
export const GET_APPOINTMENT_FAIL = 'GET_APPOINTMENT_FAIL';

export const GET_APPOINTMENTS_LOADING = 'GET_APPOINTMENTS_LOADING';
export const GET_APPOINTMENTS_SUCCESS = 'GET_APPOINTMENTS_SUCCESS';
export const GET_APPOINTMENTS_FAIL = 'GET_APPOINTMENTS_FAIL';

export const ADD_APPOINTMENT_LOADING = 'ADD_APPOINTMENT_LOADING';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAIL = 'ADD_APPOINTMENT_FAIL';

export const DELETE_APPOINTMENT_LOADING = 'DELETE_APPOINTMENT_LOADING';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL';

export const EDIT_APPOINTMENT_LOADING = 'EDIT_APPOINTMENT_LOADING';
export const EDIT_APPOINTMENT_SUCCESS = 'EDIT_APPOINTMENT_SUCCESS';
export const EDIT_APPOINTMENT_FAIL = 'EDIT_APPOINTMENT_FAIL';
